### ISSUE TITLE
Cannot read property 'each' of undefined

### ISSUE THREAD

**Issue by zhen8838** [FrontendSophie/hexo-theme-autumn#1]
我想使用您的主题，但是在我生成时报错如下
```js
TypeError: F:\Blog\gitio\themes\hexo-theme-autumn\layout\post.ejs:2
    1| <article class="post">
 >> 2|     <% page.categories.each(function (cat) { %>
    3|         <h4 class="post-cat">
    4|             <a href="<%- url_for(cat.path) %>">
    5|                 <%= cat.name %>

Cannot read property 'each' of undefined
```
请问如何解决？谢谢

**Comment by FrontendSophie** [comment]
@zhen8838 您好，感谢使用autumn主题并贡献issue。

`page.categories`报错`undefined`，可能是API有调整，已更新为`site.categories`并通过本地测试。

请更新一下最新的主题代码，如果还有问题，希望您还愿意继续提出来，谢谢！

**Comment by zhen8838** [comment]
感谢您的修复，也感谢您分享美丽的主题。祝你愉快~

**Comment by wild-flame** [comment]
@FrontendSophie @zhen8838 这个修复应该回滚。

报错的原因应该是没有设定category.

我建议添加判断来修复这个问题，而不是改成抓取 site.categories。

修改以后会抓取全站的类别，以至于 post 页出现如下的奇怪的排版。
 
![image](https://user-images.githubusercontent.com/4491950/41138699-9dfc9a1a-6b15-11e8-9b2e-455ce4bc5160.png)

同时建议把 categories 的排版由纵向改成横向。（因为也许会有用户将一篇文章设置多个 category 的情况出现。）

**Comment by FrontendSophie** [comment]
@wild-flame 非常感谢，是我理解错误，已经在 https://github.com/FrontendSophie/hexo-theme-autumn/commit/9c1393c541ae82ff9247fda2b724a791aa7ff26c 中进行了修复。issue关闭之后没有消息通知，所以过去了好久今天才看见。😂实在抱歉，望请海涵。
