### ISSUE TITLE
如何在首页能能显示一小段博客正文的内容

### ISSUE THREAD

**Issue by 3cl1p53** [FrontendSophie/hexo-theme-autumn#4]
<img width="551" alt="Screen Shot 2019-06-23 at 9 09 56 AM" src="https://user-images.githubusercontent.com/39740531/59970368-f20bbf80-9596-11e9-9bbb-626e725740b0.png">
我clone下这个theme之后，发现没有像demo一样能把正文的一小部分显示出来，请问是怎么实现的呢
<img width="718" alt="Screen Shot 2019-06-23 at 9 10 52 AM" src="https://user-images.githubusercontent.com/39740531/59970376-22535e00-9597-11e9-95c6-56ee9bfa2c6b.png">

**Comment by FrontendSophie** [comment]
请尝试在你的正文里面插入`<!-- more -->`，如下图所示：

<img width="921" alt="Screen Shot 2019-06-23 at 4 37 43 PM" src="https://user-images.githubusercontent.com/23026887/59973701-b80dde00-95d5-11e9-85bc-6446ad6b1e91.png">
