### ISSUE TITLE
How to install plugins？

### ISSUE THREAD

**Issue by Yannis175** [FrontendSophie/hexo-theme-autumn#6]
I want to add some music and comments to my blog.So How to install plugins of the music and comments?

**Comment by Yannis175** [comment]
I want the details.Thanks

**Comment by FrontendSophie** [comment]
@Yannis175  
For facebook comments: https://github.com/RichardJECooke/hexo-fbcomments
For spotify: https://github.com/ivanovyordan/hexo-tag-spotify
You can try install these plugins follow their instructions.
